spring:
  application:
    name: product-purchase-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Luz1816}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: false
    show-sql: ${DB_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: never