spring:
  application:
    name: product-purchase-service

  datasource:
    url: jdbc:mysql://localhost:3306/pps_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "*SaLuz1816*"

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: never